### ISSUE TITLE
WebPack issue

### ISSUE THREAD

**Issue by J-Cordova** [EladBezalel/material2-start#18]
After running npm install I ran ng serve and got the following error

15% building modules 42/95 modules 53 active ...de_modules\sockjs-client\lib\entry.jswebpack: wait until bundle finished: /
 86% hashingcrypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at HarmonyExportImportedSpecifierDependency.updateHash (C:\Users\jordan.cordova\Desktop\Angular\material2-start\node_modules\webpack\lib\dependencies\HarmonyExportImportedSpecifierDependency.js:144:
8)
    at C:\Users\jordan.cordova\Desktop\Angular\material2-start\node_modules\webpack\lib\DependenciesBlock.js:33:5
    at Array.forEach (native)
    at NormalModule.DependenciesBlock.updateHash (C:\Users\jordan.cordova\Desktop\Angular\material2-start\node_modules\webpack\lib\DependenciesBlock.js:32:20)
    at NormalModule.Module.updateHash (C:\Users\jordan.cordova\Desktop\Angular\material2-start\node_modules\webpack\lib\Module.js:162:41)
    at NormalModule.updateHash (C:\Users\jordan.cordova\Desktop\Angular\material2-start\node_modules\webpack\lib\NormalModule.js:327:30)
    at modules.forEach.m (C:\Users\jordan.cordova\Desktop\Angular\material2-start\node_modules\webpack\lib\Chunk.js:253:31)
    at Array.forEach (native)
    at Chunk.updateHash (C:\Users\jordan.cordova\Desktop\Angular\material2-start\node_modules\webpack\lib\Chunk.js:253:16)
    at Compilation.createHash (C:\Users\jordan.cordova\Desktop\Angular\material2-start\node_modules\webpack\lib\Compilation.js:1121:10)
    at sealPart2 (C:\Users\jordan.cordova\Desktop\Angular\material2-start\node_modules\webpack\lib\Compilation.js:605:9)
    at next (C:\Users\jordan.cordova\Desktop\Angular\material2-start\node_modules\tapable\lib\Tapable.js:138:11)
    at Compilation.<anonymous> (C:\Users\jordan.cordova\Desktop\Angular\material2-start\node_modules\webpack\lib\ProgressPlugin.js:110:5)
    at next (C:\Users\jordan.cordova\Desktop\Angular\material2-start\node_modules\tapable\lib\Tapable.js:140:14)

**Comment by EladBezalel** [comment]
What node version are you using?

**Comment by J-Cordova** [comment]
6.9.2

**Comment by fad250** [comment]
I'm experiencing the same issue. My node version is v6.10.3.

**Comment by roelzkie15** [comment]
I had this same issue also using node v6.10.0

**Comment by julianobrasil** [comment]
Try this package.json (I don't know exactly which change fixed it, I'll try to find out this later):

```
{
  "name": "material2-start",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "lint": "ng lint",
    "workshop": "ts-node ./workshop-cli"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.5",
    "@angular/common": "^4.2.5",
    "@angular/compiler": "^4.2.5",
    "@angular/core": "^4.2.5",
    "@angular/flex-layout": "^2.0.0-beta.8",
    "@angular/forms": "^4.2.5",
    "@angular/http": "^4.2.5",
    "@angular/material": "2.0.0-beta.7",
    "@angular/platform-browser": "^4.2.5",
    "@angular/platform-browser-dynamic": "^4.2.5",
    "@angular/router": "^4.2.5",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.3.0",
    "zone.js": "^0.8.12"
  },
  "devDependencies": {
    "@angular/cli": "^1.2.0",
    "@angular/compiler-cli": "^4.2.5",
    "@types/jasmine": "2.5.46",
    "@types/node": "~7.0.12",
    "codelyzer": "~3.0.1",
    "simple-git": "^1.69.0",
    "simple-terminal-menu": "^1.1.3",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.4"
  }
}
```

**Comment by julianobrasil** [comment]
The main issue seems to be the lack of `"@angular/cdk": "github:angular/cdk-builds"`, along with material-builds dependency (I saw it after posting the last message). But it'll do no harm if you update the other parts too, leaving the material and flex-layout as nightly builds.

**Comment by EladBezalel** [comment]
@julianobrasil i'd love a PR

> Oh: #19
