### ISSUE TITLE
Not working out of the box, maybe dependencies issue

### ISSUE THREAD

**Issue by xavadu** [EladBezalel/material2-start#20]
Hello,

I think that it could be a dependency issue, or maybe some packages need to be upgraded. 

I clone the repository, and ran `npm install`, it finish with this error:
```
npm WARN @angular/material@2.0.0-beta.7-b00f838 requires a peer of @angular/cdk@2.0.0-beta.7-b00f838 but none was installed.
```

then when I ran `ng serve` that is the error

```
$ ng serve
Your global Angular CLI version (1.2.0) is greater than your local
version (1.0.0). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
** NG Live Development Server is running on http://localhost:4200 **
 86% hashingcrypto.js:97                                                                
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:97:16)
    at HarmonyExportImportedSpecifierDependency.updateHash (/srv/http/material2-start/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:144:8)
    at /srv/http/material2-start/node_modules/webpack/lib/DependenciesBlock.js:33:5
    at Array.forEach (native)
    at NormalModule.DependenciesBlock.updateHash (/srv/http/material2-start/node_modules/webpack/lib/DependenciesBlock.js:32:20)
    at NormalModule.Module.updateHash (/srv/http/material2-start/node_modules/webpack/lib/Module.js:162:41)
    at NormalModule.updateHash (/srv/http/material2-start/node_modules/webpack/lib/NormalModule.js:327:30)
    at modules.forEach.m (/srv/http/material2-start/node_modules/webpack/lib/Chunk.js:253:31)
    at Array.forEach (native)
    at Chunk.updateHash (/srv/http/material2-start/node_modules/webpack/lib/Chunk.js:253:16)
    at Compilation.createHash (/srv/http/material2-start/node_modules/webpack/lib/Compilation.js:1121:10)
    at sealPart2 (/srv/http/material2-start/node_modules/webpack/lib/Compilation.js:605:9)
    at next (/srv/http/material2-start/node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.<anonymous> (/srv/http/material2-start/node_modules/webpack/lib/ProgressPlugin.js:110:5)
    at next (/srv/http/material2-start/node_modules/tapable/lib/Tapable.js:140:14)
    at ExtractTextPlugin.<anonymous> (/srv/http/material2-start/node_modules/extract-text-webpack-plugin/index.js:305:5)
```

I found this related issue, it looks that a `import` is missing the file: https://github.com/webpack/webpack/issues/4072

That a pity, because the workshop looks really nice. 

Some debug info:
```
node: v8.1.2
npm: 4.6.1
os: Linux 4.11.6-1-ARCH
```

Cheers,
J.

**Comment by xavadu** [comment]
Update:

I ran `npm update` that was the output:
```
$ npm update
- async@0.9.2 node_modules/karma-webpack/node_modules/async
- loader-utils@0.2.17 node_modules/karma-webpack/node_modules/loader-utils
- lodash@3.10.1 node_modules/karma-webpack/node_modules/lodash
- source-map@0.1.43 node_modules/karma-webpack/node_modules/source-map
- loader-utils@0.2.17 node_modules/less-loader/node_modules/loader-utils
- loader-utils@0.2.17 node_modules/postcss-loader/node_modules/loader-utils
- loader-utils@0.2.17 node_modules/sass-loader/node_modules/loader-utils
- loader-utils@0.2.17 node_modules/stylus-loader/node_modules/loader-utils
- zone.js@0.7.8 node_modules/@angular/cli/node_modules/zone.js
- karma-sourcemap-loader@0.3.7 node_modules/karma-sourcemap-loader
- karma-webpack@2.0.3 node_modules/karma-webpack
material2-start@0.0.0 /srv/http/material2-start
├── @angular/cli@1.2.0 
├── @angular/flex-layout@2.0.0-beta.8  (git://github.com/angular/flex-layout-builds.git#53bf162d62a2fa990179c85e5b254a2cf837e345)
└── @angular/material@2.0.0-beta.7-b00f838  (git://github.com/angular/material2-builds.git#90f0cee417338a48f5b2b07c0e37da4ade1825a5)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/material@2.0.0-beta.7-b00f838 requires a peer of @angular/cdk@2.0.0-beta.7-b00f838 but none was installed.
```

Now `ng serve` throw a new error:
```
$ ng serve
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Hash: 488c29bd31a3fd75673b                                                              
Time: 15890ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 14.2 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 82.6 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.87 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in /srv/http/material2-start/node_modules/rxjs/Subject.d.ts (16,22): Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/core/bidi/index.d.ts (8,99): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/core/portal/portal.d.ts (8,85): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/core/portal/portal-directives.d.ts (8,76): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/core/portal/dom-portal-host.d.ts (8,31): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/core/platform/platform.d.ts (8,26): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/core/platform/features.d.ts (8,40): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/core/platform/index.d.ts (8,32): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/core/a11y/live-announcer.d.ts (8,139): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/core/a11y/focus-trap.d.ts (8,95): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/core/a11y/interactivity-checker.d.ts (8,38): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/core/a11y/fake-mousedown.d.ts (8,49): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/core/a11y/index.d.ts (8,28): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/core/keyboard/keycodes.d.ts (8,140): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/core/core.d.ts (1,99): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/core/a11y/list-key-manager.d.ts (8,44): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/sort/sort-header.d.ts (11,30): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/table/cell.d.ts (9,54): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/table/table.d.ts (1,26): Cannot find module '@angular/cdk'.

ERROR in /srv/http/material2-start/node_modules/@angular/material/typings/table/row.d.ts (1,38): Cannot find module '@angular/cdk'.

ERROR in Error encountered resolving symbol values statically. Could not resolve @angular/cdk relative to /srv/http/material2-start/node_modules/@angular/material/typings/index.d.ts., resolving symbol MaterialModule in /srv/http/material2-start/node_modules/@angular/material/typings/index.d.ts, resolving symbol MaterialModule in /srv/http/material2-start/node_modules/@angular/material/typings/index.d.ts

ERROR in ./~/@angular/material/@angular/material.es5.js
Module not found: Error: Can't resolve '@angular/cdk' in '/srv/http/material2-start/node_modules/@angular/material/@angular'
 @ ./~/@angular/material/@angular/material.es5.js 10:0-932
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.
```

Still trying to solve the issue, investigating what is cdk, it looks that is a common issue on material 2

**Comment by xavadu** [comment]
Update:

_cdk_ issue resolved after install `npm install angular/cdk-builds`

Now the missing issue to solve is:
```
$ ng serve
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Hash: 17022be850b04d89e749                                                              
Time: 16413ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 14.2 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 82.6 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 4.03 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in /srv/http/material2-start/node_modules/rxjs/Subject.d.ts (16,22): Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.

ERROR in /srv/http/material2-start/node_modules/@angular/cdk/typings/table/table.d.ts (44,22): Class 'CdkTable<T>' incorrectly implements interface 'CollectionViewer'.
  Types of property 'viewChange' are incompatible.
    Type 'BehaviorSubject<{ start: number; end: number; }>' is not assignable to type 'Observable<{ start: number; end: number; }>'.
      Types of property 'lift' are incompatible.
        Type '<R>(operator: Operator<{ start: number; end: number; }, R>) => Observable<{ start: number; end: n...' is not assignable to type '<R>(operator: Operator<{ start: number; end: number; }, R>) => Observable<R>'.
          Type 'Observable<{ start: number; end: number; }>' is not assignable to type 'Observable<R>'.
            Type '{ start: number; end: number; }' is not assignable to type 'R'.
webpack: Failed to compile.
```

**Comment by devversion** [comment]
@xavadu This is an issue of RxJS (https://github.com/ReactiveX/rxjs/issues/2539)

You can fix it easily by turning on the `noStrictGenericChecks` option from TypeScript (https://github.com/ReactiveX/rxjs/issues/2539#issuecomment-311747457)

Please let me know if you see any other issues.

**Comment by xavadu** [comment]
@DevVersion yes, I am just on that ticket and testing the posibilities, I added the `skipLibCheck: true` and/or `noStrictGenericChecks: false` but I can't have it working, maybe I am missing something:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/packages/material2-start",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noStrictGenericChecks": false,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}
``` 

I am thinking on try to downgrade typescript to 4.2.0

**Comment by devversion** [comment]
You have to set the `noStrictGenericChecks` to `true`

**Comment by xavadu** [comment]
they said to set it to `false`  https://github.com/ReactiveX/rxjs/issues/2539#issuecomment-311822548 anyway `true` or `false` still `ng serve` throw the same error

also I tried with the `skipLibCheck` options with the same result

**Comment by devversion** [comment]
@xavadu Not sure about their solution. For my personal project it worked as expected by setting to `true`, which also makes sense.

Anway, yeah I think downgrading TypeScript would work too.

**Comment by devversion** [comment]
@xavadu A Pull Request to fix this would be appreciated 😄

**Comment by xavadu** [comment]
@DevVersion  Okay, I have it working now, I will create a PR (Y)

Basically, a npm package is missing `angular/cdk-builds` and `typescript` should be forced to install the version `2.3` and not the latest version, at least untill https://github.com/ReactiveX/rxjs/issues/2539 be closed

**Comment by julianobrasil** [comment]
@xavadu , I wonder why is the cdk missing... it's in the package.json: 

`"@angular/cdk": "github:angular/cdk-builds"`

And the typescript is already fixed in 2.3.4:

`"typescript": "~2.3.4"`

At least in the branch "workshop"....

**Comment by xavadu** [comment]
@julianobrasil yes, I was seeing your PR, that solve these issues. Not sure why they are missing, but you can try to clone the repo and see that the changes are not there.

**Comment by julianobrasil** [comment]
Just cloned the repo, `npm install` and `npm start`:

![image](https://user-images.githubusercontent.com/25405143/27842206-42e39d3c-60de-11e7-817a-9151948a7855.png)

Well, got no warnings concerning angular-cli versions but my node version is 6.10.3:

```
@angular/cli: 1.2.0
node: 6.10.3
os: win32 x64
@angular/animations: 4.2.5
@angular/cdk: 2.0.0-beta.7-b00f838
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/core: 4.2.5
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/material: 2.0.0-beta.7-b00f838
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/router: 4.2.5
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.5
```

**Comment by xavadu** [comment]
@julianobrasil  I got it.

I can confirm that it is working out of the box with the `workshop` branch. 

I believe that I ran `npm run workshop` change to an older tag, and not sure why (I think because I changed my npm global folder) I executed again `npm install` over the project, and in the previous tag it was an old version of `package.json` 

So, this PR would not be necessary (Y)

**Comment by EladBezalel** [comment]
@xavadu thanks for the effort though!

**Comment by xavadu** [comment]
@EladBezalel no problem, thanks to you for this tutorial :)

**Comment by Zhuinden** [comment]
`npm install @angular/cdk` fixed it for me

**Comment by mohitvashishtha** [comment]
Try this: `npm install --save @angular/material @angular/cdk`. It solved my issue.
