### ISSUE TITLE
No longer running out of the box

### ISSUE THREAD

**Issue by JiboStore** [EladBezalel/material2-start#35]
running according to the instructions in readme:
`npm install`
`ng serve --open`

results in error:

```
> ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/less-loader/dist/cjs.js?{"sourceMap":false}!./src/main.less
> Module build failed: Error: Can't resolve '@angular/material/core/theming/prebuilt/indigo-pink.css' in '/Development/hakim/github/angular/material-start/src'
>     at onError (/Development/hakim/github/angular/material-start/node_modules/enhanced-resolve/lib/Resolver.js:61:15)
>     at loggingCallbackWrapper (/Development/hakim/github/angular/material-start/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
>     at runAfter (/Development/hakim/github/angular/material-start/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
>     at innerCallback (/Development/hakim/github/angular/material-start/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
>     at loggingCallbackWrapper (/Development/hakim/github/angular/material-start/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
>     at next (/Development/hakim/github/angular/material-start/node_modules/tapable/lib/Tapable.js:252:11)
>     at /Development/hakim/github/angular/material-start/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
>     at loggingCallbackWrapper (/Development/hakim/github/angular/material-start/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
>     at runAfter (/Development/hakim/github/angular/material-start/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
>     at innerCallback (/Development/hakim/github/angular/material-start/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
>     at loggingCallbackWrapper (/Development/hakim/github/angular/material-start/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
>     at next (/Development/hakim/github/angular/material-start/node_modules/tapable/lib/Tapable.js:252:11)
>     at innerCallback (/Development/hakim/github/angular/material-start/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
>     at loggingCallbackWrapper (/Development/hakim/github/angular/material-start/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
>     at next (/Development/hakim/github/angular/material-start/node_modules/tapable/lib/Tapable.js:249:35)
>     at resolver.doResolve.createInnerCallback (/Development/hakim/github/angular/material-start/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
>  @ ./src/main.less 4:14-187
>  @ multi ./src/main.less
> ERROR in src/app/app.component.ts(4,9): error TS2305: Module '"/Development/hakim/github/angular/material-start/node_modules/@angular/material/icon"' has no exported member 'MdIconRegistry'.
> src/app/app.module.ts(6,10): error TS2305: Module '"/Development/hakim/github/angular/material-start/node_modules/@angular/material/material"' has no exported member 'MaterialModule'.
```

**Comment by c22shen** [comment]
Yes, still the case today in July
